# Generated by Django 3.0.2 on 2020-01-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_type',
            new_name='name',
        ),
    ]
