# Generated by Django 3.0.2 on 2020-01-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200122_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='name',
            new_name='membership_type',
        ),
    ]
