# Generated by Django 3.0.3 on 2020-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membership_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='category',
            field=models.CharField(choices=[('F', 'Full'), ('O', 'Off-peak')], default='', max_length=1),
        ),
    ]
