# Generated by Django 3.0.3 on 2020-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20200406_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='category',
        ),
        migrations.AddField(
            model_name='membership',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='memberships.Category'),
            preserve_default=False,
        ),
    ]
