# Generated by Django 3.0.3 on 2020-04-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20200406_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
