# Generated by Django 3.0.2 on 2020-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200206_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address1',
            field=models.CharField(default='', max_length=100, verbose_name='Home address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Home address (Optional)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='landline',
            field=models.IntegerField(blank=True, default='', max_length=20, verbose_name='Home phone number (Optional)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(default='', max_length=20, verbose_name='Mobile number'),
        ),
    ]
