# Generated by Django 3.0.3 on 2020-03-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200311_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='landline',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='Home phone number (Optional)'),
        ),
    ]
